import Foundation
import SwiftUI

enum LocalizationKeys {
    
    // MARK: - General
    enum General {
        static let ok = "ok"
        static let done = "done"
        static let cancel = "cancel"
        static let delete = "delete"
        static let edit = "edit"
        static let save = "save"
        static let searchCards = "searchCards"
        static let noCardsAvailable = "noCardsAvailable"
        static let noAccuracyDataAvailable = "noAccuracyDataAvailable"
        static let noGrowthDataAvailable = "noGrowthDataAvailable"
        static let date = "date"
        static let accuracy = "accuracy"
        static let masteredCards = "masteredCards"
        static let invalidJSON = "invalidJSON"
        static let clearFilter = "clearFilter"
    }
    
    // MARK: - Welcome
    enum Welcome {
        static let welcomeScreenTitle = "welcomeScreenTitle"
        static let welcomeScreenMessage = "welcomeScreenMessage"
        static let myLanguage = "myLanguage"
        static let myLanguageDesc = "myLanguageDesc"
        static let imLearning = "imLearning"
        static let imLearningDesc = "imLearningDesc"
        static let continueButton = "continueButton"
        static let getStarted = "getStarted"
        static let chooseLanguages = "chooseLanguages"
        static let chooseLanguagesDesc = "chooseLanguagesDesc"
        static let readyToStart = "readyToStart"
        static let readyToStartDesc = "readyToStartDesc"
        static let featureLearning = "featureLearning"
        static let featureLearningDesc = "featureLearningDesc"
        static let featureLanguages = "featureLanguages"
        static let featureLanguagesDesc = "featureLanguagesDesc"
        static let featureSmart = "featureSmart"
        static let featureSmartDesc = "featureSmartDesc"
        static let finalFeatureAdd = "finalFeatureAdd"
        static let finalFeaturePractice = "finalFeaturePractice"
        static let finalFeatureProgress = "finalFeatureProgress"
    }
    
    // MARK: - Card
    enum Card {
        static let addCard = "addCard"
        static let addNewCard = "addNewCard"
        static let addCardButton = "addCardButton"
        static let editCard = "editCard"
        static let deleteCard = "deleteCard"
        static let deleteCardConfirmation = "deleteCardConfirmation"
        static let deleteAll = "deleteAll"
        static let deleteAllCards = "deleteAllCards"
        static let deleteAllCardsConfirmation = "deleteAllCardsConfirmation"
        static let flip = "flip"
        static let tapToGoBack = "tapToGoBack"
        static let tapToSeeFullScreen = "tapToSeeFullScreen"
        static let noCardsYet = "noCardsYet"
        static let tapToAddFirstCard = "tapToAddFirstCard"
        static let noCardsWithSelectedTag = "noCardsWithSelectedTag"
        static let noCardsFoundWithTag = "noCardsFoundWithTag"
        static let noCardsAvailable = "noCardsAvailable"
        static let noCardsFound = "noCardsFound"
        static let addFirstCardToStartLearning = "addFirstCardToStartLearning"
        static let noCardsMatchSearch = "noCardsMatchSearch"
        static let noCardsForLanguagePair = "noCardsForLanguagePair"
        static let enterTextInYourLanguage = "enterTextInYourLanguage"
        static let enterTextInTargetLanguage = "enterTextInTargetLanguage"
        static let addNotesOptional = "addNotesOptional"
        static let notes = "notes"
        static let translating = "translating"
        static let translationWillAppearHere = "translationWillAppearHere"
        static let noDifficultCards = "noDifficultCards"
        static let noDifficultCardsDescription = "noDifficultCardsDescription"
        static let difficultCards = "difficultCards"
        static let failedToCreateCard = "failedToCreateCard"
        static let cardLimitExceeded = "cardLimitExceeded"
        static let freeUsersLimitedTo = "freeUsersLimitedTo"
        static let purchaseUnlimitedCards = "purchaseUnlimitedCards"
    }
    
    // MARK: - Tag
    enum Tag {
        static let availableTags = "availableTags"
        static let noTagsAvailable = "noTagsAvailable"
        static let manageTagsInSettings = "manageTagsInSettings"
        static let toSettings = "toSettings"
        static let newTagName = "newTagName"
        static let addTag = "addTag"
        static let tagsManagement = "tagsManagement"
        static let filterByTag = "filterByTag"
        static let tagsCount = "tagsCount"
        static let noTagsAvailableAddInSettings = "noTagsAvailableAddInSettings"
    }
    
    // MARK: - Settings
    enum Settings {
        static let settings = "settings"
        static let settingsLabel = "settingsLabel"
        static let languages = "languages"
        static let voiceSettings = "voiceSettings"
        static let voiceGender = "voiceGender"
        static let maleVoice = "maleVoice"
        static let femaleVoice = "femaleVoice"
        static let cardDisplay = "cardDisplay"
        static let cardDisplayMode = "cardDisplayMode"
        static let learningMode = "learningMode"
        static let travelMode = "travelMode"
        static let learningModeDescription = "learningModeDescription"
        static let travelModeDescription = "travelModeDescription"
        static let myLanguageSettings = "myLanguageSettings"
        static let targetLanguage = "targetLanguage"
        static let theme = "theme"
        static let color = "color"
        static let backgroundStyle = "backgroundStyle"
        static let backgroundStyles = "backgroundStyles"
        static let backgroundDemo = "backgroundDemo"
        static let colorScheme = "colorScheme"
        static let colorSchemeSystem = "colorSchemeSystem"
        static let colorSchemeLight = "colorSchemeLight"
        static let colorSchemeDark = "colorSchemeDark"
        static let filterByLanguage = "filterByLanguage"
        static let filterByLanguageDescription = "filterByLanguageDescription"
        static let filterByFavorites = "filterByFavorites"
        static let showAllCards = "showAllCards"
        static let showFavoritesOnly = "showFavoritesOnly"
        static let noFavoriteCards = "noFavoriteCards"
        static let noFavoriteCardsDescription = "noFavoriteCardsDescription"
        static let previewBackgrounds = "previewBackgrounds"
        static let cardManagement = "cardManagement"
        static let cardManagementDescription = "cardManagementDescription"
        static let manageCards = "manageCards"
        static let subscriptionStatus = "subscriptionStatus"
        static let activeSubscription = "activeSubscription"
        static let manageSubscription = "manageSubscription"
        static let purchaseTesting = "purchaseTesting"
        static let testInAppPurchases = "testInAppPurchases"
        static let openPurchaseTest = "openPurchaseTest"
        static let testPurchase = "testPurchase"
        static let performTestPurchase = "performTestPurchase"
        static let transactionListenerActive = "transactionListenerActive"
        static let transactionListenerNotActive = "transactionListenerNotActive"
        static let startTestPurchase = "startTestPurchase"
        static let lastTransactionId = "lastTransactionId"
        static let transactionId = "transactionId"
        static let copyToClipboard = "copyToClipboard"
        static let copied = "copied"
        static let transactionIdCopied = "transactionIdCopied"
        static let availableProducts = "availableProducts"
        static let noProductsAvailable = "noProductsAvailable"
        static let purchasedProducts = "purchasedProducts"
        static let noProductsPurchasedYet = "noProductsPurchasedYet"
        static let purchase = "purchase"
        static let purchased = "purchased"
        static let transactionHistory = "transactionHistory"
        static let loadTransactionHistory = "loadTransactionHistory"
        static let restorePurchases = "restorePurchases"
        static let success = "success"
        static let failed = "failed"
        static let purchasesRestoredSuccessfully = "purchasesRestoredSuccessfully"
        static let failedToRestorePurchases = "failedToRestorePurchases"
        static let purchaseTestingTitle = "purchaseTestingTitle"
        static let ok = "ok"
        static let testPurchaseCompleted = "testPurchaseCompleted"
        static let testPurchaseFailed = "testPurchaseFailed"
        static let purchaseCompleted = "purchaseCompleted"
        static let purchaseFailed = "purchaseFailed"
        static let unknown = "unknown"
        static let unknownError = "unknownError"
        static let product = "product"
        static let date = "date"
    }
    
    // MARK: - Presets
    enum Presets {
        static let presetCollections = "presetCollections"
        static let seeAllCollections = "seeAllCollections"
        static let importCollection = "importCollection"
        static let importButton = "importButton"
        static let importCollectionMessage = "importCollectionMessage"
        static let noCollectionsFound = "noCollectionsFound"
        static let tryAdjustingSearch = "tryAdjustingSearch"
        static let getStartedWithCollections = "getStartedWithCollections"
        static let searchCollections = "searchCollections"
        static let allCategories = "allCategories"
        static let categoryBasics = "categoryBasics"
        static let categoryTravel = "categoryTravel"
        static let categorySocial = "categorySocial"
        static let categoryLifestyle = "categoryLifestyle"
        static let categoryProfessional = "categoryProfessional"
        static let categoryEmergency = "categoryEmergency"
        static let categoryFood = "categoryFood"
        static let categoryShopping = "categoryShopping"
        static let categoryTechnology = "categoryTechnology"
        static let categoryWeather = "categoryWeather"
        static let categoryEntertainment = "categoryEntertainment"
    }
    
    // MARK: - Paywall
    enum Paywall {
        static let unlockPremium = "unlockPremium"
        static let masterLanguageLearning = "masterLanguageLearning"
        static let usedCardsOfLimit = "usedCardsOfLimit"
        static let whatYouGetWithPremium = "whatYouGetWithPremium"
        static let unlimitedCards = "unlimitedCards"
        static let unlimitedCardsDescription = "unlimitedCardsDescription"
        static let collections = "collections"
        static let collectionsDescription = "collectionsDescription"
        static let premiumBackgrounds = "premiumBackgrounds"
        static let premiumBackgroundsDescription = "premiumBackgroundsDescription"
        static let changeLanguages = "changeLanguages"
        static let changeLanguagesDescription = "changeLanguagesDescription"
        static let restorePurchases = "restorePurchases"
        static let cancelAnytime = "cancelAnytime"
        static let terms = "terms"
        static let privacy = "privacy"
        static let goPremium = "goPremium"
        static let premium = "premium"
        static let premiumFeature = "premiumFeature"
        static let premiumRequired = "premiumRequired"
        static let premiumFeatureDescription = "premiumFeatureDescription"
        static let previewBackgrounds = "previewBackgrounds"
        static let upgradeToPremium = "upgradeToPremium"
        static let cardsRemaining = "cardsRemaining"
        static let cardsUsedOfLimit = "cardsUsedOfLimit"
        static let upgrade = "upgrade"
        static let subscription = "subscription"
        static let subscriptionStatus = "subscriptionStatus"
        static let activeSubscription = "activeSubscription"
        static let manageSubscription = "manageSubscription"
        static let upgradeToPremiumTitle = "upgradeToPremiumTitle"
        static let upgradeToPremiumMessage = "upgradeToPremiumMessage"
        static let cancel = "cancel"
        static let viewOptions = "viewOptions"
        static let unlimitedCardsTitle = "unlimitedCardsTitle"
        static let unlimitedCardsMessage = "unlimitedCardsMessage"
        static let advancedAnalyticsTitle = "advancedAnalyticsTitle"
        static let advancedAnalyticsMessage = "advancedAnalyticsMessage"
        static let customThemesTitle = "customThemesTitle"
        static let customThemesMessage = "customThemesMessage"
        static let languageChangeTitle = "languageChangeTitle"
        static let languageChangeMessage = "languageChangeMessage"
        static let cardPresetsTitle = "cardPresetsTitle"
        static let cardPresetsMessage = "cardPresetsMessage"
        static let studyModesTitle = "studyModesTitle"
        static let studyModesMessage = "studyModesMessage"
    }
    
    // MARK: - Navigation
    enum Navigation {
        static let myCards = "myCards"
        static let tagFilter = "tagFilter"
        static let shuffle = "shuffle"
        static let addCardLabel = "addCardLabel"
        static let stack = "stack"
        static let list = "list"
        static let study = "study"
        static let practice = "practice"
        static let analytics = "analytics"
        static let settings = "settings"
    }
    
    // MARK: - Languages
    enum Languages {
        static let english = "english"
        static let spanish = "spanish"
        static let french = "french"
        static let german = "german"
        static let italian = "italian"
        static let portuguese = "portuguese"
        static let dutch = "dutch"
        static let swedish = "swedish"
        static let chinese = "chinese"
        static let japanese = "japanese"
        static let korean = "korean"
        static let vietnamese = "vietnamese"
        static let russian = "russian"
        static let arabic = "arabic"
        static let hindi = "hindi"
        static let croatian = "croatian"
        static let ukrainian = "ukrainian"
    }
    
    // MARK: - About App
    enum AboutApp {
        static let about = "about"
        static let appInfo = "appInfo"
        static let tagline = "tagline"
        static let version = "version"
        static let features = "features"
        static let smartCards = "smartCards"
        static let smartCardsDescription = "smartCardsDescription"
        static let languages = "languages"
        static let languagesDescription = "languagesDescription"
        static let learningAnalytics = "learningAnalytics"
        static let learningAnalyticsDescription = "learningAnalyticsDescription"
        static let tts = "tts"
        static let ttsDescription = "ttsDescription"
        static let support = "support"
        static let supportDescription = "supportDescription"
        static let buyMeACoffee = "buyMeACoffee"
        static let legal = "legal"
        static let privacyPolicy = "privacyPolicy"
        static let termsOfService = "termsOfService"
    }
    
    // MARK: - Background Styles
    enum BackgroundStyles {
        static let gradient = "gradient"
        static let lavaLamp = "lavaLamp"
        static let snow = "snow"
        static let rain = "rain"
        static let stars = "stars"
        static let bubbles = "bubbles"
        static let waves = "waves"
        static let particles = "particles"
        static let aurora = "aurora"
        static let fireflies = "fireflies"
        static let ocean = "ocean"
        static let galaxy = "galaxy"
    }
    
    // MARK: - Study
    enum Study {
        static let study = "study"
        static let practice = "practice"
        static let studyMode = "studyMode"
        static let practiceMode = "practiceMode"
        static let quickStats = "quickStats"
        static let studyOptions = "studyOptions"
        static let practiceOptions = "practiceOptions"
        static let recentActivity = "recentActivity"
        static let totalCards = "totalCards"
        static let mastered = "mastered"
        static let difficultCards = "difficultCards"
        static let studyTimeToday = "studyTimeToday"
        static let practiceTimeToday = "practiceTimeToday"
        static let startStudySession = "startStudySession"
        static let startPracticeSession = "startPracticeSession"
        static let practiceAllCards = "practiceAllCards"
        static let practiceDifficultCards = "practiceDifficultCards"
        static let multipleChoiceQuiz = "multipleChoiceQuiz"
        static let fillInTheBlank = "fillInTheBlank"
        static let unlockAllStudyModes = "unlockAllStudyModes"
        static let unlockAllPracticeModes = "unlockAllPracticeModes"
        static let noStudyData = "noStudyData"
        static let noPracticeData = "noPracticeData"
        static let startStudyingToSeeProgress = "startStudyingToSeeProgress"
        static let startPracticingToSeeProgress = "startPracticingToSeeProgress"
        static let toCards = "toCards"
        static let totalStudyTime = "totalStudyTime"
        static let totalPracticeTime = "totalPracticeTime"
        static let averageSession = "averageSession"
        static let learningProgress = "learningProgress"
        static let exit = "exit"
        static let showAnswer = "showAnswer"
        static let incorrect = "incorrect"
        static let correct = "correct"
        static let studySessionComplete = "studySessionComplete"
        static let practiceSessionComplete = "practiceSessionComplete"
        static let accuracy = "accuracy"
        static let cardsStudied = "cardsStudied"
        static let cardsPracticed = "cardsPracticed"
        static let timeSpent = "timeSpent"
        static let studyAgain = "studyAgain"
        static let practiceAgain = "practiceAgain"
        static let done = "done"
        static let selectCorrectTranslation = "selectCorrectTranslation"
        static let fillInMissingWord = "fillInMissingWord"
        static let completeSentence = "completeSentence"
        static let chooseCorrectWord = "chooseCorrectWord"
        static let correctAnswer = "correctAnswer"
        static let translateTo = "translateTo"
        static let studyProgress = "studyProgress"
        static let practiceProgress = "practiceProgress"
    }
    
    // MARK: - Analytics
    enum Analytics {
        static let analytics = "analytics"
        static let detailedAnalytics = "detailedAnalytics"
        static let today = "today"
        static let noAnalyticsData = "noAnalyticsData"
        static let startStudyingToSeeProgress = "startStudyingToSeeProgress"
        static let unlockAdvancedAnalytics = "unlockAdvancedAnalytics"
        static let detailedProgressReports = "detailedProgressReports"
        static let detailedProgressReportsDescription = "detailedProgressReportsDescription"
        static let performanceInsights = "performanceInsights"
        static let performanceInsightsDescription = "performanceInsightsDescription"
        static let studyTimeAnalytics = "studyTimeAnalytics"
        static let studyTimeAnalyticsDescription = "studyTimeAnalyticsDescription"
        static let upgradeToPremium = "upgradeToPremium"
        static let recentActivity = "recentActivity"
        static let viewAll = "viewAll"
        static let noRecentActivity = "noRecentActivity"
        static let studySessionsWillAppearHere = "studySessionsWillAppearHere"
        static let lastStudySession = "lastStudySession"
        static let cardsStudiedToday = "cardsStudiedToday"
        static let studyStreak = "studyStreak"
        static let totalStudyTime = "totalStudyTime"
        static let cardsMastered = "cardsMastered"
        static let todaysStudy = "todaysStudy"
        static let time = "time"
        static let cardsStudied = "cardsStudied"
        static let sessions = "sessions"
        static let accuracy = "accuracy"
        static let studyTime = "studyTime"
        static let practiceTime = "practiceTime"
        static let timeRange = "timeRange"
        static let masteryProgress = "masteryProgress"
        static let mastered = "mastered"
        static let learning = "learning"
        static let needsReview = "needsReview"
        static let week = "week"
        static let month = "month"
        static let year = "year"
        static let allTime = "allTime"
        static let overview = "overview"
        static let performance = "performance"
        static let progress = "progress"
        static let insights = "insights"
        static let noStudyDataAvailable = "noStudyDataAvailable"
        static let analyticsTab = "analyticsTab"
        static let studyTimeTitle = "studyTimeTitle"
        static let practiceTimeTitle = "practiceTimeTitle"
        static let cardsMasteredTitle = "cardsMasteredTitle"
        static let studyStreakTitle = "studyStreakTitle"
        static let averageSessionTitle = "averageSessionTitle"
        static let consecutiveDays = "consecutiveDays"
        static let perSession = "perSession"
        static let studyPatterns = "studyPatterns"
        static let mostActiveTime = "mostActiveTime"
        static let preferredSessionLength = "preferredSessionLength"
        static let studyFrequency = "studyFrequency"
        static let languageProgress = "languageProgress"
        static let collectionSize = "collectionSize"
        static let cards = "cards"
        static let achievements = "achievements"
        static let firstSteps = "firstSteps"
        static let weekWarrior = "weekWarrior"
        static let masterLearner = "masterLearner"
        static let dedicated = "dedicated"
        static let vocabularyMaster = "vocabularyMaster"
        static let timeMaster = "timeMaster"
        static let accuracyTrends = "accuracyTrends"
        static let sessionPerformance = "sessionPerformance"
        static let averageSessionDuration = "averageSessionDuration"
        static let basedOnData = "basedOnData"
        static let cardsPerSession = "cardsPerSession"
        static let average = "average"
        static let sessionFrequency = "sessionFrequency"
        static let cardDifficultyAnalysis = "cardDifficultyAnalysis"
        static let noDifficultyDataAvailable = "noDifficultyDataAvailable"
        static let learningSpeed = "learningSpeed"
        static let cardsPerHour = "cardsPerHour"
        static let vsAverage = "vsAverage"
        static let masteryTimeline = "masteryTimeline"
        static let vocabularyGrowth = "vocabularyGrowth"
        static let totalVocabulary = "totalVocabulary"
        static let thisWeek = "thisWeek"
        static let thisMonth = "thisMonth"
        static let thisYear = "thisYear"
        static let learningMilestones = "learningMilestones"
        static let personalizedInsights = "personalizedInsights"
        static let noInsightsAvailableYet = "noInsightsAvailableYet"
        static let recommendations = "recommendations"
        static let noRecommendationsAtThisTime = "noRecommendationsAtThisTime"
        static let learningTips = "learningTips"
        static let spacedRepetition = "spacedRepetition"
        static let spacedRepetitionDescription = "spacedRepetitionDescription"
        static let activeRecall = "activeRecall"
        static let activeRecallDescription = "activeRecallDescription"
        static let contextLearning = "contextLearning"
        static let contextLearningDescription = "contextLearningDescription"
        static let studyNow = "studyNow"
        static let startReview = "startReview"
        static let browseCollections = "browseCollections"
        static let practiceMode = "practiceMode"
        static let notEnoughData = "notEnoughData"
        static let morning = "morning"
        static let afternoon = "afternoon"
        static let evening = "evening"
        static let night = "night"
        static let under10Minutes = "under10Minutes"
        static let tenTo20Minutes = "tenTo20Minutes"
        static let twentyTo30Minutes = "twentyTo30Minutes"
        static let thirtyTo60Minutes = "thirtyTo60Minutes"
        static let over60Minutes = "over60Minutes"
        static let onceThisWeek = "onceThisWeek"
        static let fewTimesThisWeek = "fewTimesThisWeek"
        static let mostDaysThisWeek = "mostDaysThisWeek"
        static let daily = "daily"
        static let veryEasy = "veryEasy"
        static let easy = "easy"
        static let medium = "medium"
        static let hard = "hard"
        static let veryHard = "veryHard"
        static let unknown = "unknown"
        static let completedStudySession = "completedStudySession"
        static let reviewedCardsInTime = "reviewedCardsInTime"
        static let recent = "recent"
        static let reachedCardsMastered = "reachedCardsMastered"
        static let greatProgressBuildingFoundation = "greatProgressBuildingFoundation"
        static let first10CardsMastered = "first10CardsMastered"
        static let sevenDayStudyStreak = "sevenDayStudyStreak"
        static let fiftyCardsMastered = "fiftyCardsMastered"
        static let thirtyDayStudyStreak = "thirtyDayStudyStreak"
        static let completed = "completed"
        static let inProgress = "inProgress"
        static let youreMostProductiveIn = "youreMostProductiveIn"
        static let studySessionsDuringThisTime = "studySessionsDuringThisTime"
        static let optimalSessionLength = "optimalSessionLength"
        static let yourSessionsShowBestResults = "yourSessionsShowBestResults"
        static let consistentLearningPattern = "consistentLearningPattern"
        static let yourStudyRoutineWorkingWell = "yourStudyRoutineWorkingWell"
        static let improvingAccuracy = "improvingAccuracy"
        static let recentAccuracyHigherThanBefore = "recentAccuracyHigherThanBefore"
        static let focusOnAccuracy = "focusOnAccuracy"
        static let recentAccuracyDecreased = "recentAccuracyDecreased"
        static let excellentProgress = "excellentProgress"
        static let masteredVocabularyPercentage = "masteredVocabularyPercentage"
        static let goodFoundation = "goodFoundation"
        static let masteredVocabularyKeepGoing = "masteredVocabularyKeepGoing"
        static let reviewDifficultCards = "reviewDifficultCards"
        static let cardsNeedMorePractice = "cardsNeedMorePractice"
        static let addMoreVocabulary = "addMoreVocabulary"
        static let masteredMostCurrentCards = "masteredMostCurrentCards"
        static let extendYourStreak = "extendYourStreak"
        static let daysAwayFromAchievement = "daysAwayFromAchievement"
        static let buildConsistency = "buildConsistency"
        static let tryToStudyDaily = "tryToStudyDaily"
        static let improveAccuracy = "improveAccuracy"
        static let accuracyPercentageFocusQuality = "accuracyPercentageFocusQuality"
        static let cardsCount = "cardsCount"
        static let sessionsPerDay = "sessionsPerDay"
    }
}

// MARK: - String Extension for Localization
extension String {
    var localized: String {
        return NSLocalizedString(self, comment: "")
    }

    var localizedKey: LocalizedStringKey {
        return LocalizedStringKey(self)
    }
    
    func localized(with arguments: CVarArg...) -> String {
        return String(format: self.localized, arguments: arguments)
    }
} 
